@echo off
echo Generating CH Lexer...
java -jar antlr-4.13.2-complete.jar -Dlanguage=Python3 src/parser/CHLexer.g4 -visitor -o src/parser

echo Generating CH Parser...
java -jar antlr-4.13.2-complete.jar -Dlanguage=Python3 src/parser/CHParser.g4 -visitor -o src/parser