# test/generators/MagicGen.py

class Generator:
    def generate(self, context):
        # 返回一段 C++ 代码
        # 这段代码定义了一个名为 get_magic_number 的函数
        return """
        // --- Generated by MagicGen Plugin ---

        int get_magic_number() {
            std::cout << "MagicGen is running!" << std::endl;
            return 777;
        }
        // ------------------------------------
        """